### ISSUE TITLE
Update to React 16

### ISSUE THREAD

**Issue by deadcoder0904** [drcmda/react-springy-parallax#14]

**Comment by drcmda** [comment]
@deadcoder0904 that will be a tough one, because animated has to update. There's an [issue waiting in their repo](https://github.com/animatedjs/animated/issues/63), but it hasn't been solved yet. 

In the meantime animated can be aliased to react-dom-animated (https://github.com/viewsdx/react-dom-animated), which would probably fix it. I'll try getting webpack to run an example with React 16, i'll update the front if i get it working.

**Comment by deadcoder0904** [comment]
Thanks @drcmda 

One question thought, why is this repo using React Internals. Can this package be implemented without using React Internals? 

I happened to know when I tried converting this to Preact & Inferno using preact-compat & inferno-compat respectively.

Also 1 strange behaviour, checkout http://weekly-plans.surge.sh/ where I'm using this package & when I open Chrome DevTools when I'm seeing the image & if I try decreasing or increasing the size of Chrome DevTools, the image disappears. Idk why this is happening. 

Of course nobody when viewing the website in production will open Chrome DevTools but its annoying to refresh page while developing

**Comment by drcmda** [comment]
@deadcoder0904 Aliasing worked, i updated readme.md on the frontpage.

`animated` is developed by Facebook, it is the official way to animate in react-native, but works for the web as well. It is an amazing library thats faster, smaller and easier to use than for instance react-motion and so on. There's hope i'll be updated - but if it isn't i would use react-motion, but i'd like to avoid it because of drastic performance regressions and larger code.

**Comment by drcmda** [comment]
@deadcoder0904 nevermind, it works now, just `yarn upgrade react-springy-parallax` no aliases needed.

**Comment by drcmda** [comment]
As for the other bug, i can't reproduce in the demo, if you open up console there and move it around, nothing bad happens. Do you use anything special, like SSR?

**Comment by deadcoder0904** [comment]
Here is the GIF 

![parallax](https://user-images.githubusercontent.com/16436270/30920918-c9c48a38-a3c2-11e7-98b4-6bd73e16e26b.gif)

**Comment by browniefed** [comment]
Latest Animated has now been updated to work with React v16.

**Comment by drcmda** [comment]
@browniefed thanks so much!

**Comment by browniefed** [comment]
I didn't do anything, it was all @lelandrichardson
